using Skender.Stock.Indicators;

namespace CryptoDataCollector.BussinesExtensions.Helper
{
    public class IndicatorsModel
    {
        public decimal[] SARFinalData { get; set; }
        public decimal[] ADFinalData { get; set; }
        public decimal[] AdOscFinalData { get; set; }
        public decimal[] AdxFinalData { get; set; }
        public decimal[] AdxrFinalData { get; set; }
        public decimal[] AROONDown { get; set; }
        public decimal[] AROONUp { get; set; }
        public decimal[] AroonOscData { get; set; }
        public decimal[] ATRData { get; set; }
        public decimal[] AvgPriceData { get; set; }
        public decimal[] BBandUpper { get; set; }
        public decimal[] BBandMiddle { get; set; }
        public decimal[] BBandLower { get; set; }
        public decimal[] BopData { get; set; }
        public decimal[] CciData { get; set; }
        public int[] Cdl2CrowsData { get; set; }
        public int[] Cdl3BlackCrowsData { get; set; }
        public int[] Cdl3InsideData { get; set; }
        public int[] Cdl3LineStrikeData { get; set; }
        public int[] Cdl3OutsideData { get; set; }
        public int[] Cdl3StarsInSouthData { get; set; }
        public int[] Cdl3WhiteSoldiersData { get; set; }
        public int[] CdlAbandonedBabyData { get; set; }
        public int[] CdlAdvanceBlockData { get; set; }
        public int[] CdlBeltHoldData { get; set; }
        public int[] CdlBreakawayData { get; set; }
        public int[] CdlClosingMarubozuData { get; set; }
        public int[] CdlConcealBabysWallData { get; set; }
        public int[] CdlCounterAttackData { get; set; }
        public int[] CdlDarkCloudCoverData { get; set; }
        public int[] CdlDojiData { get; set; }
        public int[] CdlDojiStarData { get; set; }
        public int[] CdlDragonflyDojiData { get; set; }
        public int[] CdlEngulfingData { get; set; }
        public int[] CdlEveningDojiStarData { get; set; }
        public int[] CdlEveningStarData { get; set; }
        public int[] CdlGapSideSideWhiteData { get; set; }
        public int[] CdlGravestoneDojiData { get; set; }
        public int[] CdlHammer { get; set; }
        public int[] CdlHangingMan { get; set; }
        public int[] CdlHarami { get; set; }
        public int[] CdlHaramiCross { get; set; }
        public int[] CdlHighWave { get; set; }
        public int[] CdlHikkake { get; set; }
        public int[] CdlHomingPigeon { get; set; }
        public int[] CdlIdentical3Crows { get; set; }
        public int[] CdlInNeck { get; set; }
        public int[] CdlInvertedHammer { get; set; }
        public int[] CdlKicking { get; set; }
        public int[] CdlKickingByLength { get; set; }
        public int[] CdlLadderBottom { get; set; }
        public int[] CdlLongLeggedDoji { get; set; }
        public int[] CdlLongLine { get; set; }
        public int[] CdlMarubozu { get; set; }
        public int[] CdlMatchingLow { get; set; }
        public int[] CdlMatHold { get; set; }
        public int[] CdlMorningDojiStar { get; set; }
        public int[] CdlMorningStar { get; set; }
        public int[] CdlOnNeck { get; set; }
        public int[] CdlPiercing { get; set; }
        public int[] CdlRickshawMan { get; set; }
        public int[] CdlSeparatingLines { get; set; }
        public int[] CdlShootingStar { get; set; }
        public int[] CdlShortLine { get; set; }
        public int[] CdlSpinningTop { get; set; }
        public int[] CdlStalledPattern { get; set; }
        public int[] CdlStickSandwich { get; set; }
        public int[] CdlTakuri { get; set; }
        public int[] CdlTasukiGap { get; set; }
        public int[] CdlThrusting { get; set; }
        public int[] CdlTristar { get; set; }
        public int[] CdlUnique3River { get; set; }
        public int[] CdlUpsideGap2Crows { get; set; }
        public int[] CdlXSideGap3Methods { get; set; }
        public decimal[] Cmo { get; set; }
        public decimal[] Dema { get; set; }
        public decimal[] DX { get; set; }
        public decimal[] Ema5 { get; set; }
        public decimal[] Ema9 { get; set; }
        public decimal[] Ema10 { get; set; }
        public decimal[] Ema12 { get; set; }
        public decimal[] Ema13 { get; set; }
        public decimal[] Ema20 { get; set; }
        public decimal[] Ema30 { get; set; }
        public decimal[] Ema26 { get; set; }
        public decimal[] Ema50 { get; set; }
        public decimal[] Ema100 { get; set; }
        public decimal[] Ema200 { get; set; }
        public decimal[] Kama { get; set; }
        public decimal[] Macd { get; set; }
        public decimal[] MacdSignal { get; set; }
        public decimal[] MacdHist { get; set; }
        public decimal[] MacdExt { get; set; }
        public decimal[] MacdExtSignal { get; set; }
        public decimal[] MacdExtHist { get; set; }
        public decimal[] MacdFix { get; set; }
        public decimal[] MacdFixSignal { get; set; }
        public decimal[] MacdFixHist { get; set; }
        public decimal[] Mama { get; set; }
        public decimal[] Fama { get; set; }
        public decimal[] Max { get; set; }
        public int[] MaxIndex { get; set; }
        public decimal[] MedPrice { get; set; }
        public decimal[] Mfi { get; set; }
        public decimal[] MidPoint { get; set; }
        public decimal[] MidPrice { get; set; }
        public decimal[] Min { get; set; }
        public int[] MinIndex { get; set; }
        public decimal[] MinusDI { get; set; }
        public decimal[] MinusDM { get; set; }
        public decimal[] Mom { get; set; }
        public decimal[] Natr { get; set; }
        public decimal[] Obv { get; set; }
        public decimal[] PlusDI { get; set; }
        public decimal[] PlusDM { get; set; }
        public decimal[] Ppo { get; set; }
        public decimal[] RocP { get; set; }
        public decimal[] RocR { get; set; }
        public decimal[] RocR100 { get; set; }
        public decimal[] RSI { get; set; }
        public decimal[] SarExt { get; set; }
        public decimal[] Sma5 { get; set; }
        public decimal[] Sma9 { get; set; }
        public decimal[] Sma10 { get; set; }
        public decimal[] Sma12 { get; set; }
        public decimal[] Sma13 { get; set; }
        public decimal[] Sma20 { get; set; }
        public decimal[] Sma30 { get; set; }
        public decimal[] Sma26 { get; set; }
        public decimal[] Sma50 { get; set; }
        public decimal[] Sma100 { get; set; }
        public decimal[] Sma200 { get; set; }
        public decimal[] StdDev { get; set; }
        public decimal[] StochSlow { get; set; }
        public decimal[] StochSlowD { get; set; }
        public decimal[] StochFK { get; set; }
        public decimal[] StochFD { get; set; }
        public decimal[] StochRsiFK { get; set; }
        public decimal[] StochRsiFD { get; set; }
        public decimal[] Sum { get; set; }
        public decimal[] T3 { get; set; }
        public decimal[] Tema { get; set; }
        public decimal[] TRange { get; set; }
        public decimal[] Trima { get; set; }
        public decimal[] Trix { get; set; }
        public decimal[] Tsf { get; set; }
        public decimal[] TypPrice { get; set; }
        public decimal[] UltOsc { get; set; }
        public decimal[] Var { get; set; }
        public decimal[] WclPrice { get; set; }
        public decimal[] WillR { get; set; }
        public decimal[] Wma { get; set; }
        public KeltnerResult[] keltnerChannels { get; set; }
        public CmfResult[] chaikinMoneyFlows { get; set; }
        public DonchianResult[] Donchian { get; set; }
        public HmaResult[] hma { get; set; }
        public AwesomeResult[] AwesomeOscillators { get; set; }
        public UltimateResult[] UltimateOscillators { get; set; }
        public VwapResult[] vwaps { get; set; }
        public IchimokuResult[] ichimokus { get; set; }



    }
}
